In [1]:
import pandas as pd

player_stats = pd.read_csv("../data/processed/player_season_stats.csv")
course_diff = pd.read_csv("../data/processed/course_difficulty.csv")

In [2]:
player_stats.shape

(2184, 17)

In [3]:
course_diff.shape

(81, 9)

In [4]:
player_stats.columns.tolist()

['season',
 'player_id',
 'player',
 'tournaments_played',
 'avg_sg_putt',
 'avg_sg_arg',
 'avg_sg_app',
 'avg_sg_ott',
 'avg_sg_t2g',
 'avg_sg_total',
 'wins',
 'top_5_finishes',
 'top_10_finishes',
 'cuts_made',
 'sg_total_rank',
 'sg_total_prev_season',
 'sg_total_delta']

In [5]:
course_diff.columns.tolist()

['course',
 'tournaments_hosted',
 'avg_strokes_vs_par',
 'avg_sg_total',
 'avg_sg_putt',
 'avg_sg_arg',
 'avg_sg_app',
 'avg_sg_ott',
 'difficulty_rank']

In [6]:
player_stats.sort_values(['season', 'sg_total_rank']).groupby('season').head(3)[
    ['season', 'player', 'avg_sg_total', 'sg_total_rank']
]

      season                player  avg_sg_total  sg_total_rank
1812    2017             Sam Burns      2.640000              1
855     2017        Dustin Johnson      2.023571              2
1591    2017        Keith Mitchell      2.000000              3
784     2018         Graham DeLaet      2.620000              1
1621    2018        Chase Seiffert      2.440000              2
856     2018        Dustin Johnson      2.247333              3
882     2019          Rory McIlroy      2.425333              1
1707    2019  Jazz Janewattananond      2.130000              2
1048    2019     Mike Lorenzo-Vera      1.880000              3
2140    2020        Davis Thompson      1.960000              1
1794    2020              Jon Rahm      1.782000              2
1580    2020             MJ Daffue      1.630000              3
1713    2021       Guido Migliozzi      2.265000              1
1795    2021              Jon Rahm      2.087059              2
1228    2021            Bud Cauley      1.890000              3
1680    2022         Cameron Smith      1.810000              1
1172    2022         Justin Thomas      1.810000              2
1105    2022           Shane Lowry      1.650000              3

In [7]:
player_stats[player_stats['sg_total_rank'] == 1][
    ['season', 'player', 'avg_sg_total', 'tournaments_played']
].sort_values('season')

      season           player  avg_sg_total  tournaments_played
1812    2017        Sam Burns      2.640000                   1
784     2018    Graham DeLaet      2.620000                   3
882     2019     Rory McIlroy      2.425333                  18
2140    2020   Davis Thompson      1.960000                   2
1713    2021  Guido Migliozzi      2.265000                   3
1680    2022    Cameron Smith      1.810000                  11

Need to add total strokes gained, and set a threshold for average strokes gained leaderboard

In [8]:
player_stats['tournaments_played'].describe()

count    2184.000000
mean       13.055403
std         9.464844
min         1.000000
25%         3.000000
50%        14.000000
75%        22.000000
max        34.000000
Name: tournaments_played, dtype: float64

In [9]:
player_stats['tournaments_played'].quantile([0.1, 0.25, 0.5, 0.75, 0.9])

0.10     1.0
0.25     3.0
0.50    14.0
0.75    22.0
0.90    25.0
Name: tournaments_played, dtype: float64