Exploration after 2nd round of processing (no changes to course difficulty data, exclusively player season exploration)

In [2]:
import pandas as pd

player_stats = pd.read_csv("../data/processed/player_season_stats.csv")
player_stats.shape
player_stats.columns.tolist()

['season',
 'player_id',
 'player',
 'tournaments_played',
 'avg_sg_putt',
 'avg_sg_arg',
 'avg_sg_app',
 'avg_sg_ott',
 'avg_sg_t2g',
 'avg_sg_total',
 'sum_sg_putt',
 'sum_sg_arg',
 'sum_sg_app',
 'sum_sg_ott',
 'sum_sg_t2g',
 'sum_sg_total',
 'wins',
 'top_5_finishes',
 'top_10_finishes',
 'cuts_made',
 'avg_sg_putt_rank',
 'avg_sg_arg_rank',
 'avg_sg_app_rank',
 'avg_sg_ott_rank',
 'avg_sg_t2g_rank',
 'avg_sg_total_rank',
 'sum_sg_putt_rank',
 'sum_sg_arg_rank',
 'sum_sg_app_rank',
 'sum_sg_ott_rank',
 'sum_sg_t2g_rank',
 'sum_sg_total_rank',
 'sg_total_prev_season',
 'sg_total_delta']

In [3]:
# Confirm sub-10-tournament players have null avg ranks but populated sum ranks
player_stats[player_stats['tournaments_played'] < 10][
    ['season', 'player', 'tournaments_played', 'avg_sg_total_rank', 'sum_sg_total_rank']
].head(10)

,season,player,tournaments_played,avg_sg_total_rank,sum_sg_total_rank
53,2017,Jonathan Byrd,7,NaN,54
60,2017,Martin Kaymer,9,NaN,61
64,2017,Henrik Norlander,5,NaN,65
67,2017,Tommy Fleetwood,9,NaN,68
69,2017,Bernd Wiesberger,9,NaN,70
71,2017,Rafael Campos,4,NaN,72
72,2017,Sam Burns,1,NaN,73
74,2017,Keith Mitchell,1,NaN,75
76,2017,Peter Uihlein,7,NaN,77
79,2017,Maverick McNealy,3,NaN,80

In [4]:
player_stats[player_stats['avg_sg_total_rank'] <= 3].sort_values(['season', 'avg_sg_total_rank'])[
    ['season', 'player', 'avg_sg_total', 'avg_sg_total_rank', 'tournaments_played']
]

,season,player,avg_sg_total,avg_sg_total_rank,tournaments_played
0,2017,Dustin Johnson,2.023571,1.0,20
2,2017,Paul Casey,1.805000,2.0,23
1,2017,Jon Rahm,1.732667,3.0,22
322,2018,Dustin Johnson,2.247333,1.0,20
323,2018,Justin Thomas,1.862500,2.0,22
327,2018,Tiger Woods,1.532000,3.0,19
665,2019,Rory McIlroy,2.425333,1.0,18
672,2019,Adam Scott,1.576154,2.0,17
669,2019,Patrick Cantlay,1.548750,3.0,20
1051,2020,Jon Rahm,1.782000,1.0,16
1052,2020,Xander Schauffele,1.515000,2.0,19
1055,2020,Justin Thomas,1.428125,3.0,19
1426,2021,Jon Rahm,2.087059,1.0,20
1427,2021,Patrick Cantlay,1.685263,2.0,22
1428,2021,Bryson DeChambeau,1.678333,3.0,21
1851,2022,Cameron Smith,1.810000,1.0,11
1847,2022,Justin Thomas,1.810000,2.0,14
1862,2022,Shane Lowry,1.650000,3.0,10

In [5]:
player_stats[player_stats['sum_sg_total_rank'] <= 3].sort_values(['season', 'sum_sg_total_rank'])[
    ['season', 'player', 'sum_sg_total', 'sum_sg_total_rank', 'tournaments_played']
]

,season,player,sum_sg_total,sum_sg_total_rank,tournaments_played
0,2017,Dustin Johnson,28.33,1,20
1,2017,Jon Rahm,25.99,2,22
2,2017,Paul Casey,25.27,3,23
322,2018,Dustin Johnson,33.71,1,20
323,2018,Justin Thomas,29.80,2,22
324,2018,Webb Simpson,24.71,3,24
665,2019,Rory McIlroy,36.38,1,18
666,2019,Hideki Matsuyama,27.97,2,24
667,2019,Sungjae Im,26.61,3,34
1051,2020,Jon Rahm,26.73,1,16
1052,2020,Xander Schauffele,24.24,2,19
1053,2020,Harris English,23.50,3,20
1426,2021,Jon Rahm,35.48,1,20
1427,2021,Patrick Cantlay,32.02,2,22
1428,2021,Bryson DeChambeau,30.21,3,21
1847,2022,Justin Thomas,21.72,1,14
1848,2022,Scottie Scheffler,21.17,2,16
1849,2022,Mito Pereira,20.73,3,20